apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
spec:
  ports:
    - port: 80
  selector:
    app: website
---
apiVersion: v1
kind: Service
metadata:
  name: website-two
  labels:
    app: website-two
spec:
  ports:
    - port: 80
  selector:
    app: website-two