apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
spec:
  rules:
    - host: ajokubauskas.com
      http:
        paths:
          - backend:
              serviceName: website
              servicePort: 80
            path: /
    - host: website5.ajokubauskas.com
      http:
        paths:
          - backend:
              serviceName: website-two
              servicePort: 80
            path: /
    # This section is only required if TLS is to be enabled for the Ingress
    # tls:
    #     - hosts:
    #         - www.example.com
    #       secretName: example-tls
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: example-tls
#   namespace: foo
# data:
#   tls.crt: <base64 encoded cert>
#   tls.key: <base64 encoded key>
# type: kubernetes.io/tls
