apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: pod-reporter
  labels:
    app: pod-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-reporter
  template:
    metadata:
      labels:
        app: pod-reporter
    spec:
      containers: 
        - name: pod-reporter
          image: whoatedacakeidid/reporter:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_URL
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: postgres.url
            - name: SCHEMA
              value: "public"
            - name: TIMEOUT
              value: "1000"